from app.profiles.search_profile import SearchProfile


mack_profile = SearchProfile(
    name="Mack - Early Career Tech Roles",
    job_titles=[
        "software engineer",
        "software developer",
        "frontend developer",
        "frontend engineer",
        "backend developer",
        "backend engineer",
        "full stack developer",
        "full stack engineer",
        "web developer",
        "application developer",
        "technical support engineer",
        "support engineer",
        "product support engineer",
        "solutions engineer",
        "implementation engineer",
        "integration engineer",
        "technical consultant",
        "customer engineer",
        "platform support engineer",
    ],
    keywords=[
        "react",
        "typescript",
        "python",
        "fastapi",
        "spring boot",
        "java",
        "postgresql",
        "sql",
        "api",
        "saas",
        "linux",
        "integration",
        "automation",
        "support",
        "customer-facing",
    ],
    locations=[
        "remote",
        "united states",
        "usa",
        "colorado",
        "denver",
    ],
    experience_levels=[
        "junior",
        "associate",
        "entry level",
        "new grad",
        "0-3 years",
        "early career",
    ],
    excluded_titles=[
        "senior",
        "staff",
        "principal",
        "manager",
        "director",
        "lead",
    ],
    excluded_companies=[],
    remote_only=False,
    allowed_locations=[
        "remote",
        "remote - us",
        "united states",
        "usa",
        "us",
        "u.s.",
        "u.s.a",
        "americas",
        "north america",
        "colorado",
        "denver",
    ],
    excluded_locations=[
        "india",
        "china",
        "singapore",
        "ireland",
        "united kingdom",
        "london",
        "europe",
        "european union",
        "europe timezone",
    ],
)